### ISSUE TITLE
js2xml repository missing

### ISSUE THREAD

**Issue by wglasshusain** [robrighter/node-recurly#12]
Hi,

My NodeJs application has a dependency on node-recurly.  I can not build my app with "npm install" as js2xml seems to have disappeared from github.

```
9467 error Error: Command failed: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-valorkin-js2xml-9c1b9dd3'...
9467 error warning: expected SRV RR, found RR type 1
9467 error fatal: remote error:
9467 error   Repository not found.
9467 error
9467 error     at ChildProcess.exithandler (child_process.js:647:15)
9467 error     at ChildProcess.EventEmitter.emit (events.js:98:17)
9467 error     at maybeClose (child_process.js:753:16)
9467 error     at Socket.<anonymous> (child_process.js:966:11)
9467 error     at Socket.EventEmitter.emit (events.js:95:17)
9467 error     at Pipe.close (net.js:465:12)
9468 error If you need help, you may report this *entire* log,
9468 error including the npm and node versions, at:
9468 error     <http://github.com/npm/npm/issues>
9469 error System Linux 3.13.0-24-generic
9470 error command "/usr/bin/node" "/usr/bin/npm" "install"
```

When I visit https://github.com/valorkin/js2xml
I receive a 404.

**Comment by lukaswhite** [comment]
I'm having exactly the same issue. Tempted to recreate the library (which I have locally) and fork the project for now.

**Comment by natew** [comment]
Also getting this, this is crazy for it to be down over a month for a company that sells this service.

**Comment by cgerrior** [comment]
Hi @natew,

[Recurly](https://www.recurly.com) does not maintain this library. That being said, other [forks](https://github.com/breadbaker/node-recurly) of this library appear to fix this particular issue. An updated version of the library is even available on [NPM](https://www.npmjs.com/package/node-recurly-updated).

-Charlie (Recurly Sales Engineer)
