### ISSUE TITLE
Error with latest Node

### ISSUE THREAD

**Issue by ajachu** [robrighter/node-recurly#5]
Hi
     I get this error on require ('node-recurly') with node v0.10.24.

Error: Cannot find module 'xml2js/lib'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at ...../node_modules/node-recurly/lib/recurly.js:3:16
    at ...../node_modules/node-recurly/lib/recurly.js:151:3)

Please let me know how to fix this...

**Comment by ejrusch** [comment]
Looks like the js2xml doesn't exist anymore... Need to change package.json.

This library is the same.

Change:
```javascript
 "dependencies" : {
    "xml2js": ">= 0.4.0",
    "js2xml": "valorkin/js2xml"
}
```
To:
```javascript
"js2xml": "philjackson/js2xml"
```
